<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard extends CI_Controller {
	function __construct() {
		parent::__construct();

		if (!$this->ion_auth->logged_in()) {
			redirect('auth/login');
		}
		
		$this->load->model('Campanha');
		$this->load->model('Operacao');
		$this->load->helper('data');
		$this->user_id 		= $this->session->user_id;
	}

	function index() {	
		$this->load->library('form_validation');
		$this->form_validation->set_rules('camp_chosen','Campaign','required|integer');
		if ($this->form_validation->run()) {
			// -----------------------------------------------------
			// CAMPAIGN
			// -----------------------------------------------------
			$camp_id		= $_POST['camp_chosen'];
			$dbchosencamp 		= $this->Campanha->get_campanha($camp_id);
			$dat_begin		= date_create($dbchosencamp['cam_inicio']);
			$dat_end		= date_create($dbchosencamp['cam_fim']);
			$time 			= date_diff($dat_end,$dat_begin)->days;

			$invest 		= $dbchosencamp['cam_investimento'];
			$goal			= $dbchosencamp['cam_objetivo'];
			$interest_rate		= ((pow(($goal/$invest),(1/$time)))-1)*100;

			$proc 			= array();
			$time_now 		= $dat_begin;
			for ($s=0; $s <= $time; $s++) {
				
				if ($s == 0) {
					$proc[] = $invest;
				} else {
					$proc[] = $proc[$s-1]*(1+($interest_rate/100));
				}
				$line1[$time_now->format('d/m/Y')] = $proc[$s];
				$time_now->modify('+1 day');
			}
			$data['dbchosencamp']	= $dbchosencamp;
			$data['path']		= $line1;

			

			// -----------------------------------------------------
			// OPERATIONS
			// -----------------------------------------------------
			$dbchosenoper 					= $this->Operacao->get_operacoes_camp($camp_id);
			if ( count($dbchosenoper) > 0) {
				foreach ($dbchosenoper as $value) {
					$profitability[]			= $value['ope_saldo'];
					$history[data_port($value['ope_dia'])] 	= $value['ope_saldo'];
					$history_data[] 			= data_port($value['ope_dia']);

				}
			} else {
				$history[data_port($dbchosencamp['cam_inicio'])] 	= $invest;
				$profitability[]					= $invest;
				$history_data[] 					= data_port($dbchosencamp['cam_inicio']);
			}
			
			$reference 	= array_keys($line1);
			$x 		= 0;
			foreach ($reference as $key => $value1) {
				if (array_search($value1, $history_data)) {
					$x++;
				}
				$line2[] 	= $profitability[$x];
			}
			$data['history'] 	= $history;
			$data['operate'] 	= $line2;
		}

		$data['dballcamp'] 	= $this->Campanha->get_campanha_user($this->user_id);
		$data['_view'] 		= 'dashboard';
		$data['button'] 	= 'OK';
		$this->load->view('layouts/main',$data);
	}
}
