<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Diasuteis extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if (!$this->ion_auth->logged_in()) {
            redirect('auth/login');
        }

    }

    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('diasuteis/index?');
        $this->pagination->initialize($config);

        $data['_view'] = 'diasuteis/index';
        $this->load->view('layouts/main', $data);
    }
}