<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Operacoes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!$this->ion_auth->logged_in())
        {
            redirect('auth/login');
        }
        $this->load->model('Operacao');
    } 

    /*
     * Listing of operacoes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('operaco/index?');
        $config['total_rows'] = $this->Operacao->get_all_operacoes_count();
        $this->pagination->initialize($config);

        $data['operacoes'] = $this->Operacao->get_all_operacoes($params);
        
        $data['_view'] = 'operacoes/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new operaco
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ope_campanha' => $this->input->post('ope_campanha'),
				'ope_saldo' => $this->input->post('ope_saldo'),
				'ope_dia' => data_banco($this->input->post('ope_dia')),
            );
            
            $operaco_id = $this->Operacao->add_operaco($params);
            redirect('operacoes/index');
        }
        else
        {
			$this->load->model('Campanha');
			$data['all_campanhas'] = $this->Campanha->get_all_campanhas();
            
            $data['_view'] = 'operacoes/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a operaco
     */
    function edit($ope_id)
    {   
        // check if the operaco exists before trying to edit it
        $data['operaco'] = $this->Operacao->get_operaco($ope_id);
        
        if(isset($data['operaco']['ope_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ope_campanha' => $this->input->post('ope_campanha'),
					'ope_saldo' => $this->input->post('ope_saldo'),
					'ope_dia' => $this->input->post('ope_dia'),
                );

                $this->Operacao->update_operaco($ope_id,$params);            
                redirect('operacoes/index');
            }
            else
            {
				$this->load->model('Campanha');
				$data['all_campanhas'] = $this->Campanha->get_all_campanhas();

                $data['_view'] = 'operacoes/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The operaco you are trying to edit does not exist.');
    } 

    /*
     * Deleting operaco
     */
    function remove($ope_id)
    {
        $operaco = $this->Operacao->get_operaco($ope_id);

        // check if the operaco exists before trying to delete it
        if(isset($operaco['ope_id']))
        {
            $this->Operacao->delete_operaco($ope_id);
            redirect('operacoes/index');
        }
        else
            show_error('The operaco you are trying to delete does not exist.');
    }
    
}
