<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Campanha extends CI_Model {
	function __construct() {
		parent::__construct();
	}

	function get_campanha($cam_id) {
		return $this->db->get_where('campanhas',array('cam_id'=>$cam_id))->row_array();
	}

	function get_all_campanhas_count() {
		$this->db->from('campanhas');
		return $this->db->count_all_results();
	}

//	 function get_all_campanhas($params = array()) {
//	 	$this->db->order_by('cam_id', 'desc');
//	 	if(isset($params) && !empty($params)) {
//	 		$this->db->limit($params['limit'], $params['offset']);
//	 	}
//	 	return $this->db->get('campanhas')->result_array();
//	 }


	function add_campanha($params) {
		$this->db->insert('campanhas',$params);
		return $this->db->insert_id();
	}

	function update_campanha($cam_id,$params) {
		$this->db->where('cam_id',$cam_id);
		return $this->db->update('campanhas',$params);
	}

	function delete_campanha($cam_id) {
		return $this->db->delete('campanhas',array('cam_id'=>$cam_id));
	}


	// ---------------------------------------------------------------------
	// ADDED
	// ---------------------------------------------------------------------
	function get_all_campanhas($params = array(),$user_id) {
		$this->db->where('cam_user', $user_id);
		$this->db->order_by('cam_id', 'desc');
		if(isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		return $this->db->get('campanhas')->result_array();
	}

	function get_campanha_user($user_id) {
		$this->db->where('cam_user', $user_id);
		return $this->db->get('campanhas')->result_array();
	}
}
