<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Operacao extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get operaco by ope_id
     */
    function get_operaco($ope_id)
    {
        return $this->db->get_where('operacoes',array('ope_id'=>$ope_id))->row_array();
    }
    
    /*
     * Get all operacoes count
     */
    function get_all_operacoes_count()
    {
        $this->db->from('operacoes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all operacoes
     */
    function get_all_operacoes($params = array())
    {
        $this->db->order_by('ope_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('operacoes')->result_array();
    }
        
    /*
     * function to add new operaco
     */
    function add_operaco($params)
    {
        $this->db->insert('operacoes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update operaco
     */
    function update_operaco($ope_id,$params)
    {
        $this->db->where('ope_id',$ope_id);
        return $this->db->update('operacoes',$params);
    }
    
    /*
     * function to delete operaco
     */
    function delete_operaco($ope_id)
    {
        return $this->db->delete('operacoes',array('ope_id'=>$ope_id));
    }
}
