<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Operacao extends CI_Model {
	function __construct() {
		parent::__construct();
	}


	function get_operacoes($ope_id) {
		return $this->db->get_where('operacoes',array('ope_id'=>$ope_id))->row_array();
	}


	function get_all_operacoes_count() {
		$this->db->from('operacoes');
		return $this->db->count_all_results();
	}


	// function get_all_operacoes($params = array()) {
	// 	// Added these two lines bellow:
	// 	$this->db->select('ope_id,ope_saldo,ope_dia,first_name,cam_nome,');
	// 	$this->db->join('campanhas','ope_campanha = cam_id');
	// 	$this->db->join('users','ope_user = id');
		
	// 	$this->db->order_by('ope_id', 'desc');
	// 	if(isset($params) && !empty($params)) {
	// 		$this->db->limit($params['limit'], $params['offset']);
	// 	}
	// 	return $this->db->get('operacoes')->result_array();
	// }


	function add_operacoes($params) {
		$this->db->insert('operacoes',$params);
		return $this->db->insert_id();
	}


	function update_operacoes($ope_id,$params) {
		$this->db->where('ope_id',$ope_id);
		return $this->db->update('operacoes',$params);
	}


	function delete_operacoes($ope_id) {
		return $this->db->delete('operacoes',array('ope_id'=>$ope_id));
	}

	// ---------------------------------------------------------------------
	// ADDED
	// ---------------------------------------------------------------------
	function get_operacoes_camp($camp_id) {
		$this->db->where('ope_campanha',$camp_id);
		return $this->db->get('operacoes')->result_array();
	}

	function get_all_operacoes($params = array(),$user_id) {
		// Added these two lines bellow:
		$this->db->select('ope_id,ope_saldo,ope_dia,first_name,cam_nome,');
		$this->db->where('ope_user',$user_id);
		$this->db->join('campanhas','ope_campanha = cam_id');
		$this->db->join('users','ope_user = id');
		$this->db->order_by('ope_id', 'desc');
		if(isset($params) && !empty($params)) {
			$this->db->limit($params['limit'], $params['offset']);
		}
		return $this->db->get('operacoes')->result_array();
	}

	function get_last_operation($id) {
		$this->db->where('ope_campanha',$id);
		$this->db->order_by('ope_id','desc');
		$this->db->limit('1');
		return $this->db->get('operacoes')->row_array();
	}
}
